#!/usr/bin/env ruby
 
site 'http://community.opscode.com/api/v1'
 
cookbook 'apt'
cookbook 'git'
cookbook 'build-essential'
cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm.git',
  :ref => 'v0.8.6'

